### ISSUE TITLE
testdetails not according to API

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/HSHS-DOMXSS-Scanner#16]
Please see your testdetails:

```JSON
[{
  "name": "CONTENT_SECURITY_POLICY",
  "hasError": false,
  "errorMessage": null,
  "score": 100,
  "scoreType": "warning",
  "testDetails": [{
    "placeholder": "HEADER",
    "values": ["default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';"]
  }, {
    "placeholder": "CSP_CORRECT"
  }]
}, {
  "name": "CONTENT_TYPE",
  "hasError": false,
  "errorMessage": null,
  "score": 100,
  "scoreType": "warning",
  "testDetails": [{
    "placeholder": "HEADER",
    "values": ["text\\/html; charset=utf-8"]
  }, {
    "placeholder": "CT_CORRECT"
  }]
}, {
  "name": "PUBLIC_KEY_PINS",
  "hasError": false,
  "errorMessage": null,
  "score": 100,
  "scoreType": "bonus",
  "testDetails": [{
    "placeholder": "HEADER",
    "values": ["pin-sha256=\\"
      base64 + primary == \\"; pin-sha256=\\"
      base64 + backup == \\"; max-age=5184000; includeSubDomains"
    ]
  }, {
    "placeholder": "HPKP_MORE_15"
  }, {
    "placeholder": "INCLUDE_SUBDOMAINS"
  }]
}, {
  "name": "STRICT_TRANSPORT_SECURITY",
  "hasError": false,
  "errorMessage": null,
  "score": 100,
  "scoreType": "warning",
  "testDetails": [{
    "placeholder": "HEADER",
    "values": ["max-age=31536000; includeSubDomains"]
  }, {
    "placeholder": "HSTS_MORE_6"
  }, {
    "placeholder": "INCLUDE_SUBDOMAINS"
  }]
}, {
  "name": "X_CONTENT_TYPE_OPTIONS",
  "hasError": false,
  "errorMessage": null,
  "score": 100,
  "scoreType": "warning",
  "testDetails": [{
    "placeholder": "HEADER",
    "values": ["nosniff"]
  }, {
    "placeholder": "XCTO_CORRECT"
  }]
}, {
  "name": "X_FRAME_OPTIONS",
  "hasError": false,
  "errorMessage": null,
  "score": 100,
  "scoreType": "warning",
  "testDetails": [{
    "placeholder": "HEADER",
    "values": ["sameorigin"]
  }, {
    "placeholder": "XFO_CORRECT"
  }]
}, {
  "name": "X_XSS_PROTECTION",
  "hasError": false,
  "errorMessage": null,
  "score": 100,
  "scoreType": "warning",
  "testDetails": [{
    "placeholder": "HEADER",
    "values": ["1; mode=block"]
  }, {
    "placeholder": "XXSS_CORRECT"
  }, {
    "placeholder": "XXSS_BLOCK"
  }]
}]
```

Please compare your testdetails with the api. "values" has to be an associative array.

Additionally using  "HEADER" only makes sense if the text should always be the same for each test.

**Comment by Lednerb** [comment]
The `HEADER` is sent for technical information (as it was requested some time ago) so the user can see what header is actually set (without a manual request (via `curl -v domain.com` for example). 

Which `key` should the `values` associative array have for the `HEADER` information, although the complete `values` field should be displayed?

Or do you request to delete the `HEADER` information completely because it's not either used on siwecos?

**Comment by Skeeve** [comment]
Hi Sascha. I know what it is for. The issue is: The datastructure is wrong.

You send:

```JSON
  "testDetails": [{
    "placeholder": "HEADER",
    "values": ["text\\/html; charset=utf-8"]
  }, {
    "placeholder": "CT_CORRECT"
  }]
```

Expected is something like:

```JSON
  "testDetails": [{
    "placeholder": "HEADER",
    "values": {
      "type":"text\\/html; charset=utf-8",
      "site":"https://your.do.main"
    }
  }, {
    "placeholder": "CT_CORRECT"
  }]
```

and in this case

HEADER shold be defined as the text (completely made up and maybe wrong, but it's about the syntax, not the semantics) "We found the wrong header %type% at url '%site%'".

CT_CORRECT should be defined as some static thext like "Content-Type is set according to best practices".

I hope you already see here what I meant with "Additionally using "HEADER" only makes sense if the text should always be the same for each test.".

The "placeholder"s are defined globally. So there can only be one text for "HEADER" which is shared among all scanners (this might be something we should change, but that's a different matter). The key-value pairs in "values" on the other hand are locally defined by you and can be reused in other testdetails as often as you like.
