### ISSUE TITLE
x-frame-options false positive

### ISSUE THREAD

**Issue by SniperSister** [SIWECOS/HSHS-DOMXSS-Scanner#19]
Hi,

die aktuelle Live Version erkennt laut Testdetail Meldungen bei dieser Seite hier einen mehrfach gesetzten x-frame-options header, de-facto wird aber garkeiner gesetzt:
https://www.dr-menzel-it.de/

**Comment by Lednerb** [comment]
Error is here:

https://github.com/SIWECOS/HSHS-DOMXSS-Scanner/blob/aedb7ac266b1748c58d84af24f4e510caaf7f496/app/Ratings/XFrameOptionsRating.php#L25-L26

Placeholder should be `HEADER_NOT_SET`

Related to #17

**Comment by Lednerb** [comment]
done by #20
