### ISSUE TITLE
The return of the malformed json output

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/HSHS-DOMXSS-Scanner#21]
The current version on production gives wrongly encoded results.

See:

    "testDetails":[{"placeholder":"CT_META_TAG_SET_CORRECT","values":{"META":"<meta http-equiv=\\"Content-Type\\" content=\\"text\\/html; charset=UTF-8\\">"}}

Too many backslashes.

formatting with with json_pp throws

    , or } expected while parsing object/hash, at character offset 393 (before "Content-Type\\\\" co...") at /usr/bin/json_pp5.18 line 45.

**Comment by SniperSister** [comment]
How can I reproduce this? My test domain returned correct results

**Comment by Lednerb** [comment]
Also please ensure that the deployed version matches the actual `master`.

**Comment by Skeeve** [comment]
I wish every scanner would have an api call which would tell its version…

**Comment by Skeeve** [comment]
Newest version is deployed.

Actual outout is

```JSON
{"name":"HEADER","hasError":false,"errorMessage":null,"score":10,"tests":[{"name":"CONTENT_SECURITY_POLICY","hasError":true,"errorMessage":"HEADER_NOT_SET","score":0,"scoreType":"warning","testDetails":[]},{"name":"CONTENT_TYPE","hasError":false,"errorMessage":null,"score":60,"scoreType":"warning","testDetails":[{"placeholder":"CT_META_TAG_SET_CORRECT","values":{"META":"<meta http-equiv=\\"Content-Type\\" content=\\"text\\/html; charset=UTF-8\\">"}},{"placeholder":"CT_HEADER_WITHOUT_CHARSET","values":{"HEADER":"text\\/html"}}]},{"name":"PUBLIC_KEY_PINS","hasError":true,"errorMessage":"HEADER_NOT_SET","score":0,"scoreType":"bonus","testDetails":[]},{"name":"STRICT_TRANSPORT_SECURITY","hasError":true,"errorMessage":"HEADER_NOT_SET","score":0,"scoreType":"warning","testDetails":[{"placeholder":"HEADER_NOT_SET","values":[]}]},{"name":"X_CONTENT_TYPE_OPTIONS","hasError":true,"errorMessage":"HEADER_NOT_SET","score":0,"scoreType":"warning","testDetails":[]},{"name":"X_FRAME_OPTIONS","hasError":true,"errorMessage":"HEADER_NOT_SET","score":0,"scoreType":"warning","testDetails":[{"placeholder":"HEADER_SET_MULTIPLE_TIMES","values":[]}]},{"name":"X_XSS_PROTECTION","hasError":true,"errorMessage":"HEADER_NOT_SET","score":0,"scoreType":"warning","testDetails":[{"placeholder":"HEADER_NOT_SET","values":[]}]}]}
```

Parsing this with json_pp gives the same error I've shown above.

**Comment by SniperSister** [comment]
Again: how can I reproduce this?

**Comment by Lednerb** [comment]
@Skeeve Newest version with bug fixes is #20 and not merged into the master branch yet...

**Comment by SniperSister** [comment]
As discussed on Slack, the scanner output is correct, no false JSON formatting

**Comment by Skeeve** [comment]
Thanks @SniperSister for checking
