### ISSUE TITLE
No correct Header JSON response in current master

### ISSUE THREAD

**Issue by Weegy** [SIWECOS/HSHS-DOMXSS-Scanner#22]
After merging the current dev to master, no valid JSON response is given by the HEADER Scanner, DOMXSS works fine. @Lednerb

**Comment by Weegy** [comment]
for your information only @Skeeve

**Comment by SniperSister** [comment]
What does “invalid” mean in this case? No response at all? Syntax error? JSON doesn’t fit our expectation?

**Comment by Weegy** [comment]
After testing it on staging I can tell you more. Just made a deploy this morning , and no response was received by the callback mechansim. This can be in fact invalid scheme and/or not expected format.

**Comment by Lednerb** [comment]
Is this still a thing or can this issue get closed by the actual deployed version?
