### ISSUE TITLE
Strange result X-Frame

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/HSHS-DOMXSS-Scanner#23]
This seems illogical to me:

      {
         "hasError" : true,
         "name" : "X_FRAME_OPTIONS",
         "score" : 0,
         "errorMessage" : "HEADER_NOT_SET",
         "scoreType" : "warning",
         "testDetails" : [
            {
               "values" : [],
               "placeholder" : "HEADER_SET_MULTIPLE_TIMES"
            }
         ]
      },

HEADER_NOT_SET seems to be the exact opposite of HEADER_SET_MULTIPLE_TIMES

Could you please clarify/fix?

Checking with curl (my private .de domain) shows that X-Frame isn't set at all.

**Comment by Lednerb** [comment]
Is this still an issue in the actual deployed version?
#20 was done correctly, so this should also be fixed.

**Comment by Skeeve** [comment]
Works.
