### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/HSHS-DOMXSS-Scanner#30]
We should implement a Version number for all scanners and the API so we can quickly see which version is used (or deployed).

**Comment by Lednerb** [comment]
@Skeeve @Weegy @SniperSister 

I would recommend adding a `"version": "1.0.0",` key-value pair to the generated json at the top level as follows:

```
{
  "name": "HEADER",
  "version": "1.0.0",
  "hasError": false,
  "errorMessage": null,
  "score": 66,
  "tests": [
    {
      "name": "CONTENT_SECURITY_POLICY",
      "hasError": true,
      "errorMessage": "HEADER_NOT_SET",
      "score": 0,
      "scoreType": "warning",
      "testDetails": []
    },

 ...
```

This change should not break the business-layer or core-api?

What do you think?

**Comment by Lednerb** [comment]
@ic0ns @y-ates 
how would you like to handle it?

**Comment by ic0ns** [comment]
lgtm

**Comment by y-ates** [comment]
reasonable to add and handle it like shown above
