### ISSUE TITLE
HSHS hasError properties

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/HSHS-DOMXSS-Scanner#39]
When an HSHS scan is done and no error getting the site's headers occurred, the global `hasError` is set to `false`.

If there is an Error at a specific test, for example, the `CSPRating`, the test's `hasError` is set to `true`.

Should the global `hasError` also set to `true` if one of the included ratings/tests get an error or is the global one reserved for *bigger* problems?

What do you think @SniperSister @Weegy @Skeeve ?

**Comment by Skeeve** [comment]
Let's discuss this in our next meeting.

**Comment by Lednerb** [comment]
global `hasError` if at least one test `hasError: true`
