### ISSUE TITLE
DOMXSS 500 nach deployment

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/HSHS-DOMXSS-Scanner#49]
Hi!
Nach Deployment gibt der DOMXSS beim Aufruf HTTP 500 zurück.

Achtung! Deployed wurde in der Cloud. Bitte @Weegy nach Details fragen.

**Comment by Lednerb** [comment]
@Weegy, bitte erneut -korrekt- von `development` auf `staging` deployen.

im Scan Result wird dann `"version": "1.2.0"` enthalten sein.
