### ISSUE TITLE
Scoring seems wrong

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/HSHS-DOMXSS-Scanner#6]
A scan of https://siwecos.de shows below result

![bildschirmfoto 2018-03-20 um 12 54 42](https://user-images.githubusercontent.com/725404/37653220-6286b8e6-2c3e-11e8-923c-5cf00e69c9ec.png)

So no sinks found and no sources found. Nevertheless a score of 0.

**Comment by Lednerb** [comment]
Fixed. Logical error - my fault.
