### ISSUE TITLE
HPKP Rating

### ISSUE THREAD

**Issue by SniperSister** [SIWECOS/HSHS-DOMXSS-Scanner#8]
HPKP ist bei unserer Zielgruppe eine ziemlich gefährliche Nummer, ich würde daher vorschlagen den auf "Bonus" zu setzen und damit nur anzuzeigen (und im Rating einzubeziehen) wenn er gesetzt ist - wenn HPKP fehlt, sollte SIWECOS sonst einfach ignorieren.

**Comment by Lednerb** [comment]
ScoreType ist bereits `info`.

Gerade weil auch der Browser-Support für HPKP angepasst wird, sollte das nur als info oder eben "Bonus" gewertet werden.

Also von `info` auf `bonus` switchen?

**Comment by SniperSister** [comment]
Ja, durch "bonus" wird es:
- wenn es auf Score 0 steht in der SPA ignoriert und in der Calculation geskipped
- wenn der Score auf 100 steht in der SPA angezeigt und als Verbesserung für den Score gewertet

**Comment by Lednerb** [comment]
Done.
